const IMAGES = {
    LOAD:'IMAGE_LOAD',
    LOAD_SUCCESS:'IMAGES_LOAD_SUCCESS',
    LOAD_FAIL:'IMAGES_LOAD_FAIL'
}

const STATS = {
    LOAD:'LOAD',
    LOAD_SUCCESS:'LOAD_SUCCESS',
    LOAD_FAIL:'LOAD_FAIL'
}

export {IMAGES,STATS}